version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.18.4
    steps:
      - checkout
      - install-golangci-lint
      - run:          
          command: |
            make assets
            echo "Checking if 'make assets' was ran after adding files..."
            git diff --exit-code
      - run: make verify-gomod
      - run: make check-style
      - run: make test

workflows:
  version: 2
  untagged-build:
    jobs:
      - test
